services:
  pg:
    image: postgres:16
    container_name: blps-pg
    environment:
      POSTGRES_DB: study
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blps-app
    environment:
      DB_URL: jdbc:postgresql://pg:5432/study
      DB_USER: user
      DB_PASSWORD: user
      SERVER_PORT: 1488
    ports:
      - "1488:1488"

volumes:
  pgdata:
